### Create interviewer
POST http://localhost:3000/api/v1/interviewers
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Kowalski"
}

### Get all interviewers
GET http://localhost:3000/api/v1/interviewers
Content-Type: application/json
